{
    'name': 'Odoo All In One Custom Report Layout | Odoo Font Size Report | Odoo Report Font Size | Odoo Font Style Reports | Odoo Report Font Change | Odoo Custom Report Layout | Odoo Report Layout Change | Odoo PDF Custom Design',
    'summary': 'Transform Odoo reports with custom font size, style, layouts, and stylish headers.',
    'category': 'Extra Tools',
    'version': '18.0.1.2.4',
    'author': 'Keypress IT Services',
    'website': 'https://www.keypress.co.in',
    'maintainer': 'Keypress IT Services',
    'depends': ['base', 'web', 'base_setup'],
    'data': [
        'security/ir.model.access.csv',
        'views/custom_font_style_views.xml',
        'views/kits_layout.xml',
        'views/doc_name_layout.xml',
        'views/diagonal_layout.xml',
        'views/curved_layout.xml',
        'views/abstract_layout.xml',
        'views/styles_company_report.xml',
        'views/ir_attachment_view.xml',
        'views/ir_assets_view.xml',
        'views/ir_config_parameter.xml',
        'data/report_layout_record.xml',
        'wizard/base_document_layout.xml',
    ],
    'assets': {
        'web.report_assets_common': [
            'kits_all_in_one_custom_layout/static/src/report_layout_assets/layout_kits.scss',
            'kits_all_in_one_custom_layout/static/src/report_layout_assets/lyout_doc_name.scss',
            'kits_all_in_one_custom_layout/static/src/report_layout_assets/layout_diagonal.scss',
            'kits_all_in_one_custom_layout/static/src/report_layout_assets/layout_curved.scss',
            'kits_all_in_one_custom_layout/static/src/report_layout_assets/layout_abstract.scss',
        ]
    },
    'application': True,
    'installable': True,
    'auto_install': False,
    'images': ['static/description/banner.png'],
    'price': 49.99,
    'description': 'Customize your Odoo reports effortlessly with personalized fonts, stylish layouts, and dynamic headers. Enhance readability and branding with an all-in-one report customization solution for Odoo.\n\n',
    'pre_init_hook': 'kits_pre_init_hook',
    'post_init_hook': 'kits_post_init_hook',
    'uninstall_hook': 'kits_uninstall_hook',
    'currency': 'USD',
    'license': 'OPL-1',
    'support': 'support@keypress.co.in',
}
